[versions]
agp = "8.13.0"
composeMaterial3 = "1.10.0-alpha05"
composeMultiplatform = "1.10.1"
detekt = "1.23.8"
kermit = "2.0.8"
kotest = "6.0.7"
kotlin = "2.3.0"
kotlinpoet = "2.2.0"
kotlinxCoroutines = "1.10.2"
kotlinxIo = "0.8.2"
kotlinxSerialization = "1.9.0"
ktfmt = "0.25.0"
skie = "0.10.10"
lifecycleCompose = "2.8.4"
mavenPublish = "0.36.0"
wgpu4k = "0.2.0-SNAPSHOT"
wgpu4kCommit = "c8bc79db72e16bdc4c82f51c98e283d53db56fb8"
wgpu4kRepo = "hyeons-lab/wgpu4k"
wgpu4kNativeCommit = "1b1578a1a9c8c8447763125c6de03c9bcb18af38"
wgpu4kNativeRepo = "hyeons-lab/wgpu4k-native"
webgpuKtypesCommit = "213ff3d22213e58cc4f2f59e69b1c42e0816c4d1"
webgpuKtypesRepo = "hyeons-lab/webgpu-ktypes"

# SDK versions
compileSdk = "36"
minSdk = "28"
targetSdk = "36"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleCompose" }
wgpu4k = { module = "io.ygdrasil:wgpu4k", version.ref = "wgpu4k" }
wgpu4k-toolkit = { module = "io.ygdrasil:wgpu4k-toolkit", version.ref = "wgpu4k" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
